name: Android

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-example-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      EXPO_NO_DOTENV: '1'
      EXPO_PUBLIC_VRTX_CLIENT_ID: ${{ vars.PUBLIC_DEMO_CLIENT_ID }}
      EXPO_PUBLIC_VRTX_CLIENT_SECRET: ${{ vars.PUBLIC_DEMO_CLIENT_SECRET }}
      EXPO_PUBLIC_VRTX_ENVIRONMENT: SANDBOX
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: example/package-lock.json

      - name: Install example dependencies
        run: npm ci --ignore-scripts
        working-directory: example

      - name: Generate Android project
        run: npm run prebuild -- --platform android --no-install
        working-directory: example

      - name: Set up Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb #v6.3.0
        with:
          # Pull requests reuse the cache populated by main; only main writes
          # new cache entries after a successful build.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: example/android

      - name: Set Android SDK path
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
        working-directory: example/android

      - name: Build Android release app
        run: ./gradlew app:assembleRelease --build-cache
        working-directory: example/android
        env:
          NODE_ENV: production

      - name: Upload APK artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: android-apk
          path: example/android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
          compression-level: 0
          retention-days: 7
